"""Initial migration

Revision ID: 461ac7284893
Revises: 
Create Date: 2026-04-17 10:57:19.276479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '461ac7284893'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cedula', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('apellido', sa.String(), nullable=False),
    sa.Column('entidad', sa.Enum('ALCALDIA', 'INSTITUTO_AUTONOMO', name='entidadpersonal'), nullable=True),
    sa.Column('nombre_instituto', sa.String(), nullable=True),
    sa.Column('cargo', sa.String(), nullable=True),
    sa.Column('activo', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personal_cedula'), 'personal', ['cedula'], unique=True)
    op.create_index(op.f('ix_personal_id'), 'personal', ['id'], unique=False)
    op.create_table('usuarios_sistema',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('nombre_completo', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('rol', sa.Enum('DEV', 'ADMIN', 'PORTERO', name='rolusuario'), nullable=True),
    sa.Column('activo', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_usuarios_sistema_id'), 'usuarios_sistema', ['id'], unique=False)
    op.create_index(op.f('ix_usuarios_sistema_username'), 'usuarios_sistema', ['username'], unique=True)
    op.create_table('asistencia_accesos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cedula_identidad', sa.String(), nullable=False),
    sa.Column('tipo_persona', sa.Enum('PERSONAL', 'VISITANTE', name='tipopersona'), nullable=False),
    sa.Column('hora_entrada', sa.DateTime(), nullable=True),
    sa.Column('hora_salida', sa.DateTime(), nullable=True),
    sa.Column('motivo', sa.String(), nullable=True),
    sa.Column('piso_destino', sa.String(), nullable=True),
    sa.Column('observaciones', sa.String(), nullable=True),
    sa.Column('registrado_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['registrado_por'], ['usuarios_sistema.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asistencia_accesos_cedula_identidad'), 'asistencia_accesos', ['cedula_identidad'], unique=False)
    op.create_index(op.f('ix_asistencia_accesos_id'), 'asistencia_accesos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asistencia_accesos_id'), table_name='asistencia_accesos')
    op.drop_index(op.f('ix_asistencia_accesos_cedula_identidad'), table_name='asistencia_accesos')
    op.drop_table('asistencia_accesos')
    op.drop_index(op.f('ix_usuarios_sistema_username'), table_name='usuarios_sistema')
    op.drop_index(op.f('ix_usuarios_sistema_id'), table_name='usuarios_sistema')
    op.drop_table('usuarios_sistema')
    op.drop_index(op.f('ix_personal_id'), table_name='personal')
    op.drop_index(op.f('ix_personal_cedula'), table_name='personal')
    op.drop_table('personal')
    # ### end Alembic commands ###
